# Generated by Django 3.2 on 2022-09-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_likes_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_level',
            field=models.BooleanField(default=False),
        ),
    ]
