# Generated by Django 3.2 on 2022-09-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_top_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='post_images/post-landscape-1.jpg', upload_to='post_images'),
        ),
    ]
